### ISSUE TITLE
the value obtained is sometimes not appropriate

### ISSUE THREAD

**Issue by zidni0192** [Flagsmith/flagsmith-js-client#176]
Refer to this thread on discord
https://discord.com/channels/517647859495993347/1109062231477452820

when i am trying to get value from flagsmith sometimes i got null value sometimes i got correct value

**Comment by novakzaballa** [comment]
Hi @zidni0192 , I am looking into this issue.

I am able to reproduce the behavior described, but only in the initial value of the variable feature using:
`const feature = useFlags(['feature'])`
No matter the actual value of the flag in the API, the initial value of the variable `feature` is always:
```
{
  enabled: false,
  value: null
}
```
However, after that initial value, I can see a stable behavior returning the right actual value of the flag.
Could you please confirm if this is also the behavior you can see?

**Comment by novakzaballa** [comment]
In order to manage the behavior describes in the above comment, you can use [useFlagsmithLoading()](https://docs.flagsmith.com/clients/react#useflagsmithloading-api-reference) hook, which will return a LoadingState object as described [here](https://docs.flagsmith.com/clients/javascript#flagsmith-loading-state) and then can use the LoadingState `isFetching` and/or `isLoading` to have a consistent feature flag value.

Please notice that there is an issue reported with a special case when using LoadingState and the feature-flag name is not found. Please refer to this issue #182 to follow up on that special case.
