### ISSUE TITLE
Nextjs@12 SSR throws unhandledRejection: TypeError: f is not a function

### ISSUE THREAD

**Issue by m64743** [Flagsmith/flagsmith-js-client#97]
When creating a NextJS React app using `next@12.x` with SSR the application throws `unhandledRejection: TypeError: f is not a function` after compiling when importing `flagsmith` and initializing it.

**Comment by gf3** [comment]
I'm seeing this as well in next@11:

```
freshline-marketplace  | TypeError: f is not a function
freshline-marketplace  |     at /app/node_modules/.pnpm/flagsmith@1.7.3/node_modules/flagsmith/isomorphic.js:1875:20
freshline-marketplace  |     at runMicrotasks (<anonymous>)
freshline-marketplace  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by gf3** [comment]
this is where the error is originating from for me: https://github.com/Flagsmith/flagsmith-js-client/blob/167b883d1457612d08e4ad7046b3d80338bf7924/flagsmith-core.js#L279

this is because `onError` is undefined, and other uses guard with `onError && onError(...)`

the fix for now is to provide an `onError` function to `flagsmith.init(...)`, e.g.:

```ts
await flagsmit.init({
  environmentID: "...",
  onError: (error) => {
    console.error(error);
  },
});
```

**Comment by m64743** [comment]
Setting `onError` resolved it for me 👍
